# Generated by Django 5.1.3 on 2024-11-22 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_remove_listing_owner_listing_ad_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='booking_status',
            field=models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('approved', 'Подтверждено'), ('rejected', 'Отклонено')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listing',
            name='ad_type',
            field=models.CharField(choices=[('rent', 'Rent'), ('sale', 'Sale')], max_length=50),
        ),
    ]
